# Python CircleCI 2.0 configuration file
python: &python
  docker:
    - image: circleci/python:3.7
      environment:
        JWT_SECRET_KEY: 938qef923_2#@42#%Tnjd12~!±?2Jfsj53akJKJF14njweJjfiFQs

version: 2

jobs:
  build:
    <<: *python
    steps:
      - checkout
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Pipenv
          command: pip install --user pipenv
      - run:
          name: Install dependencies and module
          command: pipenv install --dev
