# Python CircleCI 2.0 configuration file
version: 2
python: &python
  docker:
    - image: circleci/python:3.7
      environment:
        JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
        TEST_DATABASE_URI: "${TEST_DATABASE_URI}"
        COVERALLS_REPO_TOKEN: "${COVERALLS_REPO_TOKEN}"

  working_directory: ~/repo
jobs:
  build:
    <<: *python
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: Set up database
          command: |
            source $(python3 -m pipenv --venv)/bin/activate
            flask db upgrade
      - run:
          name: Run tests and upload coverage
          command: |
            source $(python3 -m pipenv --venv)/bin/activate
            coverage run --source src -m pytest
            coveralls
      - store_artifacts:
          path: coverage
          prefix: coverage
